transforms: [sentencepiece]
transforms_configs:
  sentencepiece:
    src_subword_model: "$EOLE_MODEL_DIR/mistral-7b-instruct-v0.2-awq/tokenizer.model"
    tgt_subword_model: "$EOLE_MODEL_DIR/mistral-7b-instruct-v0.2-awq/tokenizer.model"

# Model info
model_path: "$EOLE_MODEL_DIR/mistral-7b-instruct-v0.2-awq"

# Inference
seed: 42
max_length: 256
batch_type: sents
batch_size: 8
world_size: 1
gpu_ranks: [0]
# world_size: 2
# gpu_ranks: [0, 1]
# parallel_mode: "tensor_parallel"
#quant_layers: ['gate_up_proj', 'down_proj', 'up_proj', 'linear_values', 'linear_query', 'linear_keys', 'final_linear']
#quant_type: "bnb_NF4"
compute_dtype: fp16
#top_k: 1
#top_p: 0.6
#temperature: 0.9
beam_size: 1
n_best: 1
profile: false
report_time: true
src: None
log_file: None
#tgt: None
