name: pictoNMT
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python=3.10

  # Core ML frameworks
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - pytorch-mutex=1.0=cpu  # Force CPU version initially

  # Scientific computing
  - numpy>=1.22.0
  - pandas>=1.4.0
  - scipy>=1.8.0

  # Image processing
  - pillow>=8.3.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0

  # Data processing
  - requests>=2.25.0
  - lmdb>=1.4.0
  - tqdm>=4.60.0

  # Machine Learning
  - scikit-learn>=1.1.0

  # Development tools
  - pytest>=7.0.0
  - jupyter
  - ipython

  # Pip for packages not available in conda
  - pip

  # Pip-only packages
  - pip:
    - transformers>=4.35.0
    - sacrebleu>=2.3.0
    - gradio>=3.0.0
    - fastapi>=0.88.0
    - uvicorn>=0.20.0
    - streamlit>=1.15.0