transforms: [sentencepiece]
transforms_configs:
  sentencepiece:
    src_subword_model: "${EOLE_MODEL_DIR}/llama2-7b-chat-hf/tokenizer.model"
    tgt_subword_model: "${EOLE_MODEL_DIR}/llama2-7b-chat-hf/tokenizer.model"

# Model
model_path: "${EOLE_MODEL_DIR}/llama2-7b-chat-hf"

# Inference
seed: 42
max_length: 256
batch_type: sents
batch_size: 8
world_size: 1
gpu_ranks: [0]
#parallel_mode: "tensor_parallel"
quant_layers: ['gate_up_proj', 'down_proj', 'up_proj', 'linear_values', 'linear_query', 'linear_keys', 'final_linear']
quant_type: "bnb_NF4"
compute_dtype: fp16
#top_k: 1
#top_p: 0.0
#temperature: 0.9
beam_size: 1
n_best: 1
report_time: true
src: None
