# configs/config.yaml
defaults:
  - _self_
  - data: default
  - model: dual_path
  - training: default
  - experiment: casi
  - hydra/launcher: submitit_slurm

seed: 42
output_dir: ${hydra:runtime.output_dir}
experiment_name: "pictonmt_default"

wandb:
  project: "pictonmt"
  entity: "rokii3-kuleuven"
  mode: "offline"

slurm:
  partition: "gpu_a100_debug"
  time: "00:30:00"
  gpus_per_node: 1
  cpus_per_task: 8
  mem_per_cpu: 16G
  job_name: ${experiment_name}
  account: "vsc37132"

hydra:
  job:
    chdir: False
  run:
    dir: .
  sweep:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}