# Model info
model_path: "${EOLE_MODEL_DIR}/llama3-8b-instruct"

# Inference
seed: 42
max_length: 256
# max_length: 1
batch_type: sents
batch_size: 4
world_size: 1
gpu_ranks: [0]
# world_size: 2
# gpu_ranks: [0, 1]
# parallel_mode: "tensor_parallel"
quant_layers: ['gate_up_proj', 'down_proj', 'up_proj', 'linear_values', 'linear_query', 'linear_keys', 'final_linear']
quant_type: "bnb_NF4"
compute_dtype: bf16
#top_k: 1
#top_p: 0.0
#temperature: 0.9
beam_size: 1
n_best: 1
report_time: true
src: None

