# configs/eole/model.yaml
model:
  architecture: transformer
  encoder:
    type: transformer
    hidden_size: 512
    layers: 6
    heads: 8
    transformer_ff: 2048
  decoder:
    type: transformer
    hidden_size: 512
    layers: 6
    heads: 8
    transformer_ff: 2048
  embeddings:
    word_vec_size: 512
    position_encoding: true
    share_embeddings: true